# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/e435/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/lge/e435/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/lge/e435/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/lge/e435/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/lge/e435/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/lge/e435/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/lge/e435/proprietary/bin/atd:system/bin/atd \
    vendor/lge/e435/proprietary/bin/cnd:system/bin/cnd \
    vendor/lge/e435/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/lge/e435/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/lge/e435/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/lge/e435/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/lge/e435/proprietary/bin/qmiproxy:system/bin/qmiproxy \
    vendor/lge/e435/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/lge/e435/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/lge/e435/proprietary/bin/sensord:system/bin/sensord \
    vendor/lge/e435/proprietary/bin/thermald:system/bin/thermald \
    vendor/lge/e435/proprietary/bin/usbhub_init:system/bin/usbhub_init \
    vendor/lge/e435/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/lge/e435/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/lge/e435/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/lge/e435/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/lge/e435/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/lge/e435/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/lge/e435/proprietary/lib/libmm-abl.so:system/lib/libmm-abl.so \
    vendor/lge/e435/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
    vendor/lge/e435/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/lge/e435/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/lge/e435/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/lge/e435/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/lge/e435/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
    vendor/lge/e435/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/lge/e435/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/lge/e435/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/lge/e435/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/lge/e435/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/lge/e435/proprietary/lib/libmm-abl-oem.so:system/lib/libmm-abl-oem.so \
    vendor/lge/e435/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/lge/e435/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/lge/e435/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/lge/e435/proprietary/lib/libmmrtpdecoder.so:system/lib/libmmrtpdecoder.so \
    vendor/lge/e435/proprietary/lib/libmm-audio-resampler.so:system/lib/libmm-audio-resampler.so \
    vendor/lge/e435/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/lge/e435/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/lge/e435/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/lge/e435/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
    vendor/lge/e435/proprietary/lib/libchromatix_imx091_preview.so:system/lib/libchromatix_imx091_preview.so \
    vendor/lge/e435/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
    vendor/lge/e435/proprietary/lib/libchromatix_imx091_video_hd.so:system/lib/libchromatix_imx091_video_hd.so \
    vendor/lge/e435/proprietary/lib/libchromatix_imx074_video_hd.so:system/lib/libchromatix_imx074_video_hd.so \
    vendor/lge/e435/proprietary/lib/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
    vendor/lge/e435/proprietary/lib/libchromatix_imx091_default_video.so:system/lib/libchromatix_imx091_default_video.so \
    vendor/lge/e435/proprietary/lib/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/lge/e435/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/lge/e435/proprietary/lib/libstagefright_soft_ddpdec.so:system/lib/libstagefright_soft_ddpdec.so \
    vendor/lge/e435/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/lge/e435/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/lge/e435/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/lge/e435/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/lge/e435/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/lge/e435/proprietary/lib/libwfcu.so:system/lib/libwfcu.so \
    vendor/lge/e435/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/lge/e435/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/lge/e435/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/lge/e435/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/lge/e435/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/lge/e435/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/lge/e435/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/lge/e435/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/lge/e435/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/lge/e435/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/lge/e435/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/lge/e435/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/lge/e435/proprietary/lib/liblgsecclk.so:system/lib/liblgsecclk.so \
    vendor/lge/e435/proprietary/lib/liblgeat.so:system/lib/liblgeat.so \
    vendor/lge/e435/proprietary/lib/liblge_security.so:system/lib/liblge_security.so \
    vendor/lge/e435/proprietary/lib/liblgdrm.so:system/lib/liblgdrm.so \
    vendor/lge/e435/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/lge/e435/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/lge/e435/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/lge/e435/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/lge/e435/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/lge/e435/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/lge/e435/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/lge/e435/proprietary/etc/init.qcom.ftm_module.sh:system/etc/init.qcom.ftm_module.sh \
    vendor/lge/e435/proprietary/etc/init.qcom.ftm_module_out.sh:system/etc/init.qcom.ftm_module_out.sh \
    vendor/lge/e435/proprietary/etc/init.qcom.ftm_module.sh:system/etc/init.qcom.ftm_module.sh \
    vendor/lge/e435/proprietary/etc/init.qcom.ftm_module_out.sh:system/etc/init.qcom.ftm_module_out.sh \
    vendor/lge/e435/proprietary/etc/init.qcom.bt.sh:system/etc/init.qcom.bt.sh \
    vendor/lge/e435/proprietary/etc/init.qcom.coex.sh:system/etc/init.qcom.coex.sh \
    vendor/lge/e435/proprietary/etc/init.qcom.fm.sh:system/etc/init.qcom.fm.sh \
    vendor/lge/e435/proprietary/etc/init.qcom.post_fs.sh:system/etc/init.qcom.post_fs.sh \
    vendor/lge/e435/proprietary/etc/init.qcom.post_boot.sh:system/etc/init.qcom.post_boot.sh \
    vendor/lge/e435/proprietary/etc/init.qcom.sdio.sh:system/etc/init.qcom.sdio.sh
